### ISSUE TITLE
1.20.1 Version Support

### ISSUE THREAD

**Issue by NolanHewitt** [AshyBoxy/CustomPotions#2]
Any chance for a 1.20.1 version?

**Comment by AshyBoxy** [comment]
I just found the 1.0.0 version of this in a backup, so I'll upload it to the GitHub releases now.

The datapack format for recipes is the same, but for potions it looks like:
```json
{
    "fallback": "Haste",
    "effects": [
        {
            "effect": "minecraft:haste",
            "length": 4200,
            "level": 3
        }
    ]
}
```

It doesn't support EMI or REI, it's much simpler but probably very buggy. I won't be uploading it to Modrinth since I don't want to properly support it.

At some point I might backport the current version, but it relies heavily on newer features of Minecraft to do a lot of the work, so it's unlikely.
